export const configuration = () => ({
    port: parseInt(process.env.PORT, 10) || 5000,
    environment: process.env.NODE_ENV,
    db_host: process.env.DB_HOST,
    db_port: parseInt(process.env.DB_PORT, 10) || 5432,
    db_user: process.env.DB_USER,
    db_pass: process.env.DB_PASS,
    db_dialect: process.env.DB_DIALECT,
    db_name: process.env.DB_NAME,
    at_secret: process.env.AT_SECRET,
    rt_secret: process.env.RT_SECRET,
    at_expiration: process.env.AT_EXPIRATION,
    rt_expiration: process.env.RT_EXPIRATION,
    salt: parseInt(process.env.SALT, 10) || 12,
    ucaller_token: process.env.UCALLER_TOKEN,
    ucaller_id: process.env.UCALLER_ID,
});
